settings:
  title: 'P치gina de estado'
  url: 'https://status.fernandodilland.com/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'Todos los sistemas se encuentran trabajando'
  notAllmonitorsOperational: 'No todos los sistemas est치n trabajando'
  monitorLabelOperational: 'Trabajando'
  monitorLabelNotOperational: 'Sin trabajar'
  monitorLabelNoData: 'Sin datos'
  dayInHistogramNoData: 'Sin datos'
  dayInHistogramOperational: 'Todo en orden'
  dayInHistogramNotOperational: ' incidente(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: www-cloudflare-com
    name: Cloudflare
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.cloudflare.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: fractory-mx
    name: Fractory
    description: 'F치brica digital de dise침o.'
    url: 'https://fractory.mx'
    method: GET
    expectStatus: 200
    linkable: true

  - id: tusemana-com
    name: TuSemana
    url: 'https://tusemana.com'
    method: GET
    expectStatus: 200
    linkable: true
